# POST a message to the RabbitMQ queue
POST http://localhost:3000/api/my_queue
Content-Type: application/json

{
    "message": "5"
}

###

# GET a message from the RabbitMQ queue with a 5-second timeout
GET http://localhost:3000/api/my_queue?timeout=3000
###

GET http://localhost:3000/api/queues

###